title: Jekyll Playground
email:
description: >-
  Just my private playground to test out this tools. No-comercial interest/value
  in this page.
baseurl: ""
url: ""
twitter_username:
github_username:  lyra2108

theme: minima
plugins:
  - jekyll-feed
  - jekyll-spaceship

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
